config/routes.rb
Rails.application.routes.draw do

 # get '/', to: "home#index"
 # get 'home/users/sign_in'

 devise_for :users, path: '', path_names: { sign_in: '/signin', sign_out: 'logout'}, :controllers => { registrations: 'registrations'}, :skip => [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #get '/home', to: "home#home"


  as :user do
  get 'edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
  put 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  devise_scope :user do
  	authenticated :user do
  		root 'home#home', as: :authenticated_root
      resources :bes_assets
      resources :bes_cyber_assets
      resources :bes_cyber_systems
      resources :network_top_to_es_perimeters
      resources :ps_perimeters
      resources :ea_points
      resources :es_perimeters do
        get 'download'
      end
      resources :psp_diagrams_to_ps_perimeters
      resources :access_list_to_ea_points
  	end

  	unauthenticated do
  		root 'devise/sessions#new', as: :unauthenticated_root
  	end
  end

end

app/models/psp_diagrams_to_ps_perimeter.rb
class PspDiagramsToPsPerimeter < ApplicationRecord
	mount_uploader :ps_pproof, PsPproofUploader
	serialize :ps_pproof, JSON 
end

app/controllers/psp_diagrams_to_ps_perimeters_controller.rb
class PspDiagramsToPsPerimetersController < ApplicationController
  before_action :set_psp_diagrams_to_ps_perimeter, only: [:show, :edit, :update, :destroy]

  # GET /psp_diagrams_to_ps_perimeters
  # GET /psp_diagrams_to_ps_perimeters.json
  def index
    if current_user.admin
    @psp_diagrams_to_ps_perimeters = PspDiagramsToPsPerimeter.all
    else 
      redirect_to "/ps_perimeters", notice: 'Page not available.'
    end
  end

  # GET /psp_diagrams_to_ps_perimeters/1
  # GET /psp_diagrams_to_ps_perimeters/1.json
  def show
    if current_user.admin
      @ps_perimeters = PsPerimeter.all
    else 
      redirect_to "/ps_perimeters", notice: 'Cannot edit uploaded document.'
    end
  end

  # GET /psp_diagrams_to_ps_perimeters/new
  def new
    @psp_diagrams_to_ps_perimeter = PspDiagramsToPsPerimeter.new
    @ps_perimeters = PsPerimeter.all
    @psp_diagrams_to_ps_perimeter.ps_pproof = params[:file]
  end

  # GET /psp_diagrams_to_ps_perimeters/1/edit
  def edit
    if current_user.admin
    @ps_perimeters = PsPerimeter.all
    else 
      redirect_to "/ps_perimeters", notice: 'Cannot edit uploaded document.'
    end
  end

  # POST /psp_diagrams_to_ps_perimeters
  # POST /psp_diagrams_to_ps_perimeters.json
  def create
    @psp_diagrams_to_ps_perimeter = PspDiagramsToPsPerimeter.new(psp_diagrams_to_ps_perimeter_params)

    respond_to do |format|
      if @psp_diagrams_to_ps_perimeter.save

        @psp_diagrams_to_ps_perimeter.ps_pproof.url # => '/url/to/file.png'
        @psp_diagrams_to_ps_perimeter.ps_pproof.current_path # => 'path/to/file.png'
        @psp_diagrams_to_ps_perimeter.ps_pproof_identifier # => 'file.png'

        format.html { redirect_to "/ps_perimeters", notice: 'Document has been uploaded.' }
        #format.html { redirect_to @psp_diagrams_to_ps_perimeter, notice: 'Psp diagrams to ps perimeter was successfully created.' }
        format.json { render :show, status: :created, location: @psp_diagrams_to_ps_perimeter }
      else
        format.html { render :new }
        format.json { render json: @psp_diagrams_to_ps_perimeter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /psp_diagrams_to_ps_perimeters/1
  # PATCH/PUT /psp_diagrams_to_ps_perimeters/1.json
  def update
    respond_to do |format|
      if @psp_diagrams_to_ps_perimeter.update(psp_diagrams_to_ps_perimeter_params)
        format.html { redirect_to @psp_diagrams_to_ps_perimeter, notice: 'Psp diagrams to ps perimeter was successfully updated.' }
        format.json { render :show, status: :ok, location: @psp_diagrams_to_ps_perimeter }
      else
        format.html { render :edit }
        format.json { render json: @psp_diagrams_to_ps_perimeter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /psp_diagrams_to_ps_perimeters/1
  # DELETE /psp_diagrams_to_ps_perimeters/1.json
  def destroy
    if current_user.admin
    @psp_diagrams_to_ps_perimeter.destroy
    respond_to do |format|
      format.html { redirect_to psp_diagrams_to_ps_perimeters_url, notice: 'Psp diagrams to ps perimeter was successfully destroyed.' }
      format.json { head :no_content }
    end
    else 
      redirect_to "/ps_perimeters", notice: 'Cannot delete uploaded document.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_psp_diagrams_to_ps_perimeter
      @psp_diagrams_to_ps_perimeter = PspDiagramsToPsPerimeter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def psp_diagrams_to_ps_perimeter_params
      params.require(:psp_diagrams_to_ps_perimeter).permit(:ps_pproof,:remove_ps_pproof,:psp_dia_file_name, :psp_dia_psp_id)
    end
end

app/helpers/psp_diagrams_to_ps_perimeters_helper.rb
module PspDiagramsToPsPerimetersHelper
end

app/views/psp_diagrams_to_ps_perimeters/_form.html.erb
  <body>
    <div class="container">
      <%= form_with(model: psp_diagrams_to_ps_perimeter, local: true) do |form| %>
      <% if psp_diagrams_to_ps_perimeter.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(psp_diagrams_to_ps_perimeter.errors.count, "error") %> prohibited this psp_diagrams_to_ps_perimeter from being saved:</h2>
        <ul>
          <% psp_diagrams_to_ps_perimeter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="form-row">

        <div class="col">
  <div class="field">
    File Name:
    <%= form.text_field :psp_dia_file_name, id: :psp_diagrams_to_ps_perimeter_psp_dia_file_name, class: "form-control" %>
  </div>
</div>

<div class="col">

  <div class="field">
    PSP ID:
        <%= form.select(:psp_dia_psp_id, @ps_perimeters.all.collect { |p| [ p.psp_id, p.id ] }, {:include_blank => true, :required=>true}, {:class => 'form-control'}) %>
  </div>

</div>

</div>

<br>


          <div class="form-row">

          <div class="col form-control">
            Attachment <strong>(PDF ONLY)</strong>:<br>
            <%= form.file_field :ps_pproof, multiple: false %>

            <p>
              <% if @psp_diagrams_to_ps_perimeter.ps_pproof? %>
              <%= image_tag(@psp_diagrams_to_ps_perimeter.ps_pproof_url, :class => "photoedit") %>
              <br>
              <%= form.check_box :remove_es_pproof %> Remove Attachment

              <% end %>

            </p>
          </div>

        </div>

<br>

  <div class="form-row text-center">
        <div class="col">
    <%= form.submit "Add File", class: "btn-taco-lg"%>
  </div>
</div>
<% end %>


</div>
</body>

app/views/psp_diagrams_to_ps_perimeters/edit.html.erb
<h1>Editing Psp Diagrams To Ps Perimeter</h1>

<%= render 'form', psp_diagrams_to_ps_perimeter: @psp_diagrams_to_ps_perimeter %>

<%= link_to 'Show', @psp_diagrams_to_ps_perimeter %> |
<%= link_to 'Back', psp_diagrams_to_ps_perimeters_path %>

app/views/psp_diagrams_to_ps_perimeters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Psp Diagrams To Ps Perimeters</h1>

<table>
  <thead>
    <tr>
      <th>Psp dia file name</th>
      <th>Psp dia psp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @psp_diagrams_to_ps_perimeters.each do |psp_diagrams_to_ps_perimeter| %>
      <tr>
        <td><%= psp_diagrams_to_ps_perimeter.psp_dia_file_name %></td>
        <td><%= psp_diagrams_to_ps_perimeter.psp_dia_psp_id %></td>
        <td><%= link_to 'Show', psp_diagrams_to_ps_perimeter %></td>
        <td><%= link_to 'Edit', edit_psp_diagrams_to_ps_perimeter_path(psp_diagrams_to_ps_perimeter) %></td>
        <td><%= link_to 'Destroy', psp_diagrams_to_ps_perimeter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Psp Diagrams To Ps Perimeter', new_psp_diagrams_to_ps_perimeter_path %>

app/views/psp_diagrams_to_ps_perimeters/new.html.erb
<div class="text-center">
	<h1 class="display-4">Adding PSP Diagram</h1>
</div>

<br>

<%= render 'form', psp_diagrams_to_ps_perimeter: @psp_diagrams_to_ps_perimeter %>

<div class="text-center">
<a href="/"  class= "btn-taco-med">Home</a>
<%= link_to 'Show PSPs', ps_perimeters_path, class: "btn-taco-med" %>
</div>

app/views/psp_diagrams_to_ps_perimeters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Psp dia file name:</strong>
  <%= @psp_diagrams_to_ps_perimeter.psp_dia_file_name %>
</p>

<p>
  <strong>Psp dia psp:</strong>
  <%= @psp_diagrams_to_ps_perimeter.psp_dia_psp_id %>
</p>

<%= link_to 'Edit', edit_psp_diagrams_to_ps_perimeter_path(@psp_diagrams_to_ps_perimeter) %> |
<%= link_to 'Back', psp_diagrams_to_ps_perimeters_path %>