config/routes.rb
Rails.application.routes.draw do

 # get '/', to: "home#index"
 # get 'home/users/sign_in'

 devise_for :users, path: '', path_names: { sign_in: '/signin', sign_out: 'logout'}, :controllers => { registrations: 'registrations'}, :skip => [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #get '/home', to: "home#home"


  as :user do
  get 'edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
  put 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  devise_scope :user do
  	authenticated :user do
  		root 'home#home', as: :authenticated_root
      resources :bes_assets
      resources :bes_cyber_assets
      resources :bes_cyber_systems
      resources :network_top_to_es_perimeters
      resources :ps_perimeters
      resources :ea_points
      resources :es_perimeters do
        get 'download'
      end
      resources :psp_diagrams_to_ps_perimeters
      resources :access_list_to_ea_points
  	end

  	unauthenticated do
  		root 'devise/sessions#new', as: :unauthenticated_root
  	end
  end

end

app/models/network_top_to_es_perimeter.rb
class NetworkTopToEsPerimeter < ApplicationRecord
	mount_uploader :es_pproof, EsPproofUploader
	serialize :es_pproof, JSON 
end

app/controllers/network_top_to_es_perimeters_controller.rb
class NetworkTopToEsPerimetersController < ApplicationController
  before_action :set_network_top_to_es_perimeter, only: [:show, :edit, :update, :destroy]


  # GET /network_top_to_es_perimeters
  # GET /network_top_to_es_perimeters.json
  def index

    if current_user.admin
      @network_top_to_es_perimeters = NetworkTopToEsPerimeter.all
    else 
      redirect_to "/es_perimeters", notice: 'Page not available.'
    end

  end

  # GET /network_top_to_es_perimeters/1
  # GET /network_top_to_es_perimeters/1.json
  def show
    if current_user.admin
      @es_perimeters = EsPerimeter.all
    else 
      redirect_to "/es_perimeters", notice: 'Cannot edit uploaded document.'
    end
  end

  # GET /network_top_to_es_perimeters/new
  def new
    @network_top_to_es_perimeter = NetworkTopToEsPerimeter.new
    @es_perimeters = EsPerimeter.all
    @network_top_to_es_perimeter.es_pproof = params[:file]
  end

  # GET /network_top_to_es_perimeters/1/edit
  def edit
    if current_user.admin
      @es_perimeters = EsPerimeter.all
    else 
      redirect_to "/es_perimeters", notice: 'Cannot edit uploaded document.'
    end

  end

  # POST /network_top_to_es_perimeters
  # POST /network_top_to_es_perimeters.json
  def create
    @network_top_to_es_perimeter = NetworkTopToEsPerimeter.new(network_top_to_es_perimeter_params)

    respond_to do |format|
      if @network_top_to_es_perimeter.save

        @network_top_to_es_perimeter.es_pproof.url # => '/url/to/file.png'
        @network_top_to_es_perimeter.es_pproof.current_path # => 'path/to/file.png'
        @network_top_to_es_perimeter.es_pproof_identifier # => 'file.png'

        format.html { redirect_to "/es_perimeters", notice: 'Document has been uploaded.' }
        #format.html { redirect_to @network_top_to_es_perimeter, notice: 'Network top to es perimeter was successfully created.' }
        format.json { render :show, status: :created, location: @network_top_to_es_perimeter }
      else
        format.html { render :new }
        format.json { render json: @network_top_to_es_perimeter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /network_top_to_es_perimeters/1
  # PATCH/PUT /network_top_to_es_perimeters/1.json
  def update

    if current_user.admin
      respond_to do |format|
      if @network_top_to_es_perimeter.update(network_top_to_es_perimeter_params)
        format.html { redirect_to @network_top_to_es_perimeter, notice: 'Network top to es perimeter was successfully updated.' }
        format.json { render :show, status: :ok, location: @network_top_to_es_perimeter }
      else
        format.html { render :edit }
        format.json { render json: @network_top_to_es_perimeter.errors, status: :unprocessable_entity }
      end
    end
    else 
      redirect_to "/es_perimeters", notice: 'Cannot edit uploaded document.'
    end

  end

  # DELETE /network_top_to_es_perimeters/1
  # DELETE /network_top_to_es_perimeters/1.json
  def destroy
    if current_user.admin
      @network_top_to_es_perimeter.destroy
    respond_to do |format|
      format.html { redirect_to network_top_to_es_perimeters_url, notice: 'Network top to es perimeter was successfully destroyed.' }
      format.json { head :no_content }
    end
    else 
      redirect_to "/es_perimeters", notice: 'Cannot delete uploaded document.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network_top_to_es_perimeter
      @network_top_to_es_perimeter = NetworkTopToEsPerimeter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_top_to_es_perimeter_params
      params.require(:network_top_to_es_perimeter).permit(:es_pproof,:remove_es_pproof,:nt_file_name, :nt_esp_id)
    end
end

app/helpers/network_top_to_es_perimeters_helper.rb
module NetworkTopToEsPerimetersHelper
end

app/views/network_top_to_es_perimeters/_form.html.erb
  <body>
    <div class="container">
      <%= form_with(model: network_top_to_es_perimeter, local: true) do |form| %>
      <% if network_top_to_es_perimeter.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(network_top_to_es_perimeter.errors.count, "error") %> prohibited this network_top_to_es_perimeter from being saved:</h2>
        <ul>
          <% network_top_to_es_perimeter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>


 <div class="form-row">

  <div class="col">

  <div class="field">
    File Name:
    <%= form.text_field :nt_file_name, id: :network_top_to_es_perimeter_nt_file_name, class: "form-control", :required=>true %>
  </div>

</div>

<div class="col">

  <div class="field">
    ESP ID:
        <%= form.select(:nt_esp_id, @es_perimeters.all.collect { |p| [ p.esp_id, p.id ] }, {:include_blank => true, :required=>true}, {:class => 'form-control'}) %>
  </div>

</div>

</div>

<br>

          <div class="form-row">

          <div class="col form-control">
            Attachment <strong>(PDF ONLY)</strong>:<br>
            <%= form.file_field :es_pproof, multiple: false %>

            <p>
              <% if @network_top_to_es_perimeter.es_pproof? %>
              <%= image_tag(@network_top_to_es_perimeter.es_pproof_url, :class => "photoedit") %>
              <br>
              <%= form.check_box :remove_es_pproof %> Remove Attachment

              <% end %>

            </p>
          </div>

        </div>

<br>

<div class="form-row text-center">
        <div class="col">
    <%= form.submit "Add File", class: "btn-taco-lg"%>
  </div>
</div>
<% end %>

</div>
</body>

app/views/network_top_to_es_perimeters/edit.html.erb
<h1>Editing Network Top To Es Perimeter</h1>

<%= render 'form', network_top_to_es_perimeter: @network_top_to_es_perimeter %>

<%= link_to 'Show', @network_top_to_es_perimeter %> |
<%= link_to 'Back', network_top_to_es_perimeters_path %>

app/views/network_top_to_es_perimeters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Network Top To Es Perimeters</h1>

<table>
  <thead>
    <tr>
      <th>Nt file name</th>
      <th>Nt esp</th>
      <th>PROOF</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @network_top_to_es_perimeters.each do |network_top_to_es_perimeter| %>
      <tr>
        <td><%= network_top_to_es_perimeter.nt_file_name %></td>
        <td><%= network_top_to_es_perimeter.nt_esp_id %></td>
        <td><%= network_top_to_es_perimeter.es_pproof %></td>
        <td><%= link_to 'Show', network_top_to_es_perimeter %></td>
        <td><%= link_to 'Edit', edit_network_top_to_es_perimeter_path(network_top_to_es_perimeter) %></td>
        <td><%= link_to 'Destroy', network_top_to_es_perimeter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Network Top To Es Perimeter', new_network_top_to_es_perimeter_path %>

app/views/network_top_to_es_perimeters/new.html.erb
<div class="text-center">
	<h1 class="display-4">Adding Network Topology</h1>
</div>

<br>

<%= render 'form', network_top_to_es_perimeter: @network_top_to_es_perimeter %>

<div class="text-center">
<a href="/"  class= "btn-taco-med">Home</a>
<%= link_to 'Show ESPs', es_perimeters_path, class: "btn-taco-med" %>
</div>

app/views/network_top_to_es_perimeters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nt file name:</strong>
  <%= @network_top_to_es_perimeter.nt_file_name %>
</p>

<p>
  <strong>Nt esp:</strong>
  <%= @network_top_to_es_perimeter.nt_esp_id %>
</p>

<%= link_to 'Edit', edit_network_top_to_es_perimeter_path(@network_top_to_es_perimeter) %> |
<%= link_to 'Back', network_top_to_es_perimeters_path %>